export type LedProductCategory = "Indoor" | "Outdoor";

export type LedProduct = {
  slug: string;
  title: string;
  category: LedProductCategory;
  pixelPitch: string;
  price: string;
  image: string;
  shortDescription: string;
  description: string;
  features: string[];
  specifications: {
    label: string;
    value: string;
  }[];
};

const ledProductData: LedProduct[] = [
  {
    slug: "outdoor-led-display-screen-price-in-bangladesh",
    title: "Outdoor LED Display Screen Price in Bangladesh",
    category: "Outdoor",
    pixelPitch: "Outdoor LED",
    price: "2,000 - 5,500",
    image:
      "/images/Outdoor-LED-Display/outdoor-led-display-screen-price-in-bangladesh.webp",
    shortDescription:
      "Outdoor LED display screen solution for Bangladesh with competitive pricing, installation, and support.",
    description:
      "The outdoor led display screen price in bangladesh product is made for businesses that need bright, durable, and high-impact outdoor advertising. It is suitable for billboards, roadside branding, building signage, commercial campaigns, and public display projects with professional installation and after-sales support.",
    features: [
      "High-brightness outdoor visibility",
      "Weather-resistant display design",
      "Suitable for billboards and roadside signage",
      "Custom screen size and structure support",
      "Installation, CMS setup, and service support",
    ],
    specifications: [
      { label: "Application", value: "Outdoor LED display screen" },
      { label: "Use Case", value: "Billboard, signage, and advertising" },
      { label: "Brightness", value: "High-brightness outdoor display" },
      { label: "Protection", value: "Outdoor weather-resistant design" },
      { label: "Screen Size", value: "Custom size supported" },
      { label: "Service", value: "Installation and after-sales support" },
    ],
  },
  {
    slug: "p1-25-cob-indoor-led-display-screen",
    title: "P1.25 COB Indoor LED Display Screen",
    category: "Indoor",
    pixelPitch: "P1.25",
    price: "10,500 - 15,000",
    image: "/images/Indoor-LED-Display/P1.25-COB-indoor-led-display-screen.webp",
    shortDescription:
      "Premium P1.25 Indoor LED Display with COB LED Display technology for ultra-clear LED Video Wall and Digital Signage projects.",
    description:
      "The P1.25 Indoor LED Display is designed for premium indoor applications where high resolution, smooth visuals, and reliable performance are essential. With a 1.25mm pixel pitch and COB LED type, it delivers sharp image quality for close viewing in conference rooms, control rooms, studios, retail spaces, and corporate environments. The module offers 256x128 pixel resolution with 640000 dots/m2 pixel density, ensuring detailed content presentation. Its 500 cd/m2 brightness, 5000:1 contrast ratio, and 140 degree horizontal and vertical viewing angle provide clear visibility from different positions. The display supports 3840Hz standard refresh rate with optional 7680Hz, making video playback smooth and flicker-free. It also supports 2K and 4K video input, 12-14 bit processing depth, and adjustable 2000K-9300K color temperature. With low typical power consumption, long 100000-hour lifespan, and international certifications, this COB LED Display is suitable for professional Indoor LED Display, Digital Signage, and LED Video Wall projects.",
    features: [
      "P1.25 fine pixel pitch for ultra-clear close-viewing",
      "COB LED technology for better durability and stable performance",
      "256x128 pixel module resolution",
      "640000 dots/m2 high pixel density",
      "500 cd/m2 brightness for indoor environments",
      "3840Hz standard refresh rate, 7680Hz optional",
      "5000:1 contrast ratio for sharp image depth",
      "2K and 4K video support",
      "100000 hours lifespan",
      "BIS, CE, CB, ROHS, and EAC certified",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "1.25mm" },
      { label: "LED Type", value: "COB" },
      { label: "Module Resolution", value: "256x128 = 32768 pixels" },
      { label: "Pixel Density", value: "640000 dots/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D16.6mm" },
      { label: "Module Weight", value: "0.48+/-0.02kg" },
      { label: "HUB", value: "HUB320" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "500 cd/m2" },
      { label: "Color Temperature", value: "2000K-9300K Adjustable" },
      { label: "Viewing Angle", value: "140 degree / 140 degree" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Max Input Power", value: "586 W/m2" },
      { label: "Typical Input Power", value: "176 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz Standard / 7680Hz Optional" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K, 4K" },
      { label: "Life Span", value: "100000 Hours" },
      { label: "Working Temperature/Humidity", value: "-20C-45C / 10%-50%RH" },
      { label: "Storage Temperature/Humidity", value: "-20C-50C / 10%-60%RH" },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p1-86-cob-indoor-led-display-screen",
    title: "P1.86 COB Indoor LED Display Screen",
    category: "Indoor",
    pixelPitch: "P1.86",
    price: "7,000 - 10,000",
    image: "/images/Indoor-LED-Display/P1.86-COB-%20indoor-LED-display-screen.webp",
    shortDescription:
      "P1.86 indoor LED display with SMD1515 LED technology, high refresh rate, and smooth close-view visuals.",
    description:
      "The P1.86 Indoor LED Display is designed for close-view indoor applications where sharp image quality, smooth playback, and reliable performance are essential. With 1.86mm pixel pitch, SMD1515 LED type, 172x86 module resolution, 3840Hz standard refresh rate, optional 7680Hz refresh rate, 450-500 cd/m2 brightness, and 5000:1 contrast ratio, this display is suitable for conference rooms, control rooms, showrooms, studios, corporate spaces, and premium indoor digital signage projects.",
    features: [
      "1.86mm fine pixel pitch for close-view indoor clarity",
      "SMD1515 LED type with 172x86 module resolution",
      "3840Hz standard refresh rate with 7680Hz optional",
      "450-500 cd/m2 brightness with 5000:1 contrast ratio",
      "2K HD and 4K UHD video support",
      "100000-hour lifespan with BIS, CE, CB, ROHS, and EAC certification",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "1.86mm" },
      { label: "LED Type", value: "SMD1515" },
      { label: "Module Resolution", value: "172x86 = 14792 Pixels" },
      { label: "Pixel Density", value: "288906 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D16mm" },
      { label: "Module Weight", value: "0.43+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "450-500 cd/m2" },
      { label: "Color Temperature", value: "2000K-9300K Adjustable" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "300 W/m2" },
      { label: "Input Power Typical", value: "90 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz Standard / 7680Hz Optional" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      { label: "Working Temperature/Humidity", value: "-20C-45C / 10%-50%RH (No Condensation)" },
      { label: "Storage Temperature/Humidity", value: "-20C-50C / 10%-60%RH (No Condensation)" },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p1-667-led-screen-panel",
    title: "P1.667 LED Screen Panel",
    category: "Indoor",
    pixelPitch: "P1.667",
    price: "8,000 - 11,500",
    image: "/images/Indoor-LED-Display/p1.667-led-screen-panel.webp",
    shortDescription:
      "High-resolution indoor LED screen panel for close-view display walls and detailed digital signage.",
    description:
      "The p1.667 led screen panel offers a clean balance of clarity, brightness, and flexible installation for indoor video walls. It is a practical choice for conference rooms, showrooms, command areas, retail displays, and branded interior screens.",
    features: [
      "Fine pixel pitch for clear text and visuals",
      "Modular panel design for custom screen sizes",
      "Consistent color and grayscale performance",
      "Wide viewing angle for indoor audiences",
      "Efficient choice for commercial indoor display walls",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "1.667 mm" },
      { label: "Application", value: "Indoor LED screen panel" },
      { label: "Viewing Distance", value: "1.6 m and above" },
      { label: "Refresh Rate", value: "Up to 3840 Hz" },
      { label: "Brightness", value: "700-1000 nits" },
      { label: "Cabinet Type", value: "Slim fixed-install cabinet" },
    ],
  },
  {
    slug: "p2-indoor-led-display-board",
    title: "P2 Indoor LED Display Board",
    category: "Indoor",
    pixelPitch: "P2",
    price: "6,000 - 8,500",
    image: "/images/Indoor-LED-Display/P2-indoor-LED-display-board.webp",
    shortDescription:
      "P2 indoor LED display with SMD1515 LED technology, high pixel density, and smooth video performance.",
    description:
      "The P2 Indoor LED Display is designed for indoor projects that need sharp image quality, smooth playback, and dependable long-term operation. With 2mm pixel pitch, SMD1515 LED type, 160x80 module resolution, 250000 dot/m2 pixel density, 450-500 cd/m2 brightness, 5000:1 contrast ratio, 3840Hz standard refresh rate, and optional 7680Hz refresh rate, it is suitable for meeting rooms, showrooms, retail displays, auditoriums, and professional indoor video wall projects.",
    features: [
      "2mm pixel pitch for sharp indoor LED display visuals",
      "SMD1515 LED type with 160x80 module resolution",
      "250000 dot/m2 high pixel density",
      "450-500 cd/m2 brightness with 5000:1 contrast ratio",
      "3840Hz standard refresh rate with 7680Hz optional",
      "2K HD and 4K UHD video support",
      "100000-hour lifespan with BIS, CE, CB, ROHS, and EAC certification",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "2mm" },
      { label: "LED Type", value: "SMD1515" },
      { label: "Module Resolution", value: "160x80 = 12800 Pixels" },
      { label: "Pixel Density", value: "250000 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D16.6mm" },
      { label: "Module Weight", value: "0.45+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "450-500 cd/m2" },
      { label: "Color Temperature", value: "2000K-9300K Adjustable" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "488 W/m2" },
      { label: "Input Power Typical", value: "163 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz Standard / 7680Hz Optional" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      { label: "Working Temperature/Humidity", value: "-20C-45C / 10%-50%RH (No Condensation)" },
      { label: "Storage Temperature/Humidity", value: "-20C-50C / 10%-60%RH (No Condensation)" },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p2-5-indoor-led-screen-panel",
    title: "P2.5 Indoor LED Screen Panel",
    category: "Indoor",
    pixelPitch: "P2.5",
    price: "5,000 - 7,000",
    image: "/images/Indoor-LED-Display/P2.5-indoor-led-screen-panel.webp",
    shortDescription:
      "P2.5 indoor LED display with SMD2121 LED technology, stable brightness, and smooth video performance.",
    description:
      "The P2.5 Indoor LED Display is a dependable indoor display solution for commercial signage, meeting rooms, retail stores, auditoriums, halls, and indoor advertising screens. With 2.5mm pixel pitch, SMD2121 LED type, 128x64 module resolution, 160000 dot/m2 pixel density, 450-500 cd/m2 brightness, 5000:1 contrast ratio, 3840Hz standard refresh rate, and optional 7680Hz refresh rate, it delivers smooth playback, clear visuals, and reliable long-term performance.",
    features: [
      "2.5mm pixel pitch for clear indoor viewing",
      "SMD2121 LED type with 128x64 module resolution",
      "450-500 cd/m2 brightness with 5000:1 contrast ratio",
      "3840Hz standard refresh rate with 7680Hz optional",
      "2K HD and 4K UHD video support",
      "100000-hour lifespan with BIS, CE, CB, ROHS, and EAC certification",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "2.5mm" },
      { label: "LED Type", value: "SMD2121" },
      { label: "Module Resolution", value: "128x64 = 8192 Pixels" },
      { label: "Pixel Density", value: "160000 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D16.6mm" },
      { label: "Module Weight", value: "0.38+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "450-500 cd/m2" },
      { label: "Color Temperature", value: "2000K-9300K Adjustable" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "488 W/m2" },
      { label: "Input Power Typical", value: "163 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz Standard / 7680Hz Optional" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      { label: "Working Temperature/Humidity", value: "-20C-45C / 10%-50%RH (No Condensation)" },
      { label: "Storage Temperature/Humidity", value: "-20C-50C / 10%-60%RH (No Condensation)" },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p3-indoor-led-display-module",
    title: "P3 Indoor LED Display Module",
    category: "Indoor",
    pixelPitch: "P3",
    price: "4,000 - 6,000",
    image: "/images/Indoor-LED-Display/p3-indoor-led-display-module.webp",
    shortDescription:
      "P3 indoor LED display with SMD2121 LED technology, reliable brightness, and smooth playback.",
    description:
      "The P3 Indoor LED Display is built for indoor signage projects where reliable brightness, stable performance, and smooth content playback are important. With 3mm pixel pitch, SMD2121 LED type, 64x64 module resolution, 102400 dot/m2 pixel density, >=500 cd/m2 brightness, 5000:1 contrast ratio, 3840Hz standard refresh rate, and optional 7680Hz refresh rate, it is suitable for shopping centers, halls, stages, display boards, retail areas, and business advertising walls.",
    features: [
      "3mm pixel pitch for practical indoor viewing distance",
      "SMD2121 LED type with 64x64 module resolution",
      "102400 dot/m2 pixel density",
      ">=500 cd/m2 brightness with 5000:1 contrast ratio",
      "3840Hz standard refresh rate with 7680Hz optional",
      "2K HD and 4K UHD video support",
      "100000-hour lifespan with BIS, CE, CB, ROHS, and EAC certification",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "3mm" },
      { label: "LED Type", value: "SMD2121" },
      { label: "Module Resolution", value: "64x64 = 4096 Pixels" },
      { label: "Pixel Density", value: "102400 dot/m2" },
      { label: "Module Size", value: "W192mm x H192mm x D14mm" },
      { label: "Module Weight", value: "0.23+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: ">=500 cd/m2" },
      { label: "Color Temperature", value: "2000K-9300K Adjustable" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "543 W/m2" },
      { label: "Input Power Typical", value: "180 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz Standard / 7680Hz Optional" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      { label: "Working Temperature/Humidity", value: "-20C-45C / 10%-50%RH (No Condensation)" },
      { label: "Storage Temperature/Humidity", value: "-20C-50C / 10%-60%RH (No Condensation)" },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p1-53-indoor-cob-led-display-panel",
    title: "P1.53 Indoor COB LED Display Panel",
    category: "Indoor",
    pixelPitch: "P1.53",
    price: "9,000 - 13,000",
    image: "/images/Indoor-LED-Display/p1.53-indoor-COB-led-display-panel.webp",
    shortDescription:
      "Fine-pitch indoor COB LED display panel for detailed presentation, retail, and control room visuals.",
    description:
      "The p1.53 indoor COB led display panel delivers sharp picture quality for professional indoor video walls. It is suitable for showrooms, meeting rooms, galleries, command centers, and customer-facing spaces where close viewing and polished visuals are important.",
    features: [
      "Fine-pitch COB LED panel design",
      "Sharp output for text, images, and video",
      "Wide viewing angle for group environments",
      "Slim cabinet profile for indoor installation",
      "Reliable option for premium digital signage",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "1.53 mm" },
      { label: "Application", value: "Indoor COB LED display panel" },
      { label: "Viewing Distance", value: "1.5 m and above" },
      { label: "Refresh Rate", value: "Up to 3840 Hz" },
      { label: "Brightness", value: "700-1000 nits" },
      { label: "Cabinet Type", value: "Slim fixed-install cabinet" },
    ],
  },
  {
    slug: "p6-led-display-screen",
    title: "P6 Outdoor LED Display Screen",
    category: "Outdoor",
    pixelPitch: "P6",
    price: "2,500 - 4,000",
    image: "/images/Outdoor-LED-Display/p6-led-display-screen.webp",
    shortDescription:
      "P6 outdoor LED display screen with SMD2727 LED technology, stable brightness, and reliable long-distance visibility.",
    description:
      "The P6 outdoor LED display screen features a 6mm pixel pitch, SMD2727 LED technology, 32x32 module resolution, 27750 dot/m2 pixel density, 4500-5000 cd/m2 brightness, 3840Hz refresh rate, and 5000:1 contrast ratio. It is a practical choice for outdoor billboards, roadside advertising, public display boards, building signage, event screens, and commercial brand promotion.",
    features: [
      "6mm pixel pitch for outdoor display applications",
      "SMD2727 LED technology with 27750 dot/m2 pixel density",
      "4500-5000 cd/m2 brightness for daylight visibility",
      "3840Hz refresh rate with 12-14 bit processing depth",
      "Reliable 100000-hour lifespan for outdoor installations",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "6mm" },
      { label: "LED Type", value: "SMD2727" },
      { label: "Module Resolution", value: "32x32 = 1024 Pixels" },
      { label: "Pixel Density", value: "27750 dot/m2" },
      { label: "Module Size", value: "W192mm x H192mm x D18mm" },
      { label: "Module Weight", value: "0.35+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "4500-5000 cd/m2" },
      { label: "Color Temperature", value: "6500K (1000K-9500K Adjustable)" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "895 W/m2" },
      { label: "Input Power Typical", value: "268 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      {
        label: "Working Temperature/Humidity",
        value: "-20C-50C / 10%-80%RH (No Condensation)",
      },
      {
        label: "Storage Temperature/Humidity",
        value: "-20C-55C / 10%-85%RH (No Condensation)",
      },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p8-led-display-module",
    title: "P8 Outdoor LED Display Module",
    category: "Outdoor",
    pixelPitch: "P8",
    price: "2,000 - 3,500",
    image: "/images/Outdoor-LED-Display/P8-led-display-module.webp",
    shortDescription:
      "P8 outdoor LED display module with SMD2727 LED technology, efficient brightness, and stable long-distance visibility.",
    description:
      "The P8 outdoor LED display module features an 8mm pixel pitch, SMD2727 LED technology, 40x20 module resolution, 15625 dot/m2 pixel density, 4000-4500 cd/m2 brightness, 3840Hz refresh rate, and 5000:1 contrast ratio. It is ideal for large billboards, road-facing signage, stadium display areas, public information boards, outdoor advertising screens, and cost-efficient outdoor video walls.",
    features: [
      "8mm pixel pitch for long-distance outdoor viewing",
      "SMD2727 LED technology with 15625 dot/m2 pixel density",
      "4000-4500 cd/m2 brightness for outdoor signage",
      "3840Hz refresh rate with 12-14 bit processing depth",
      "Reliable 100000-hour lifespan for large-format screens",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "8mm" },
      { label: "LED Type", value: "SMD2727" },
      { label: "Module Resolution", value: "40x20 = 800 Pixels" },
      { label: "Pixel Density", value: "15625 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D18.5mm" },
      { label: "Module Weight", value: "0.48+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "4000-4500 cd/m2" },
      { label: "Color Temperature", value: "6500K (1000K-9500K Adjustable)" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "879 W/m2" },
      { label: "Input Power Typical", value: "293 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      {
        label: "Working Temperature/Humidity",
        value: "-20C-50C / 10%-80%RH (No Condensation)",
      },
      {
        label: "Storage Temperature/Humidity",
        value: "-20C-55C / 10%-85%RH (No Condensation)",
      },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p4-outdoor-led-display-module",
    title: "P4 Outdoor LED Display Module",
    category: "Outdoor",
    pixelPitch: "P4",
    price: "3,500 - 5,500",
    image: "/images/Outdoor-LED-Display/p4-outdoor-led-display-module.webp",
    shortDescription:
      "P4 outdoor LED display module with SMD1921 LED technology, high brightness, and reliable outdoor performance.",
    description:
      "The P4 outdoor LED display module features a 4mm pixel pitch, SMD1921 LED technology, 80x40 module resolution, 62500 dot/m2 pixel density, 5000-5500 cd/m2 brightness, 3840Hz refresh rate, and 5000:1 contrast ratio. It is suitable for outdoor billboards, building signage, roadside advertising, commercial displays, and public information screens that need bright, stable, and long-lasting visual performance.",
    features: [
      "4mm pixel pitch for clear outdoor viewing",
      "SMD1921 LED technology with 62500 dot/m2 pixel density",
      "5000-5500 cd/m2 brightness for outdoor visibility",
      "3840Hz refresh rate with 12-14 bit processing depth",
      "Reliable 100000-hour lifespan for commercial installations",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "4mm" },
      { label: "LED Type", value: "SMD1921" },
      { label: "Module Resolution", value: "80x40 = 3200 Pixels" },
      { label: "Pixel Density", value: "62500 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D18.4mm" },
      { label: "Module Weight", value: "0.49+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "5000-5500 cd/m2" },
      { label: "Color Temperature", value: "6500K (1000K-9500K Adjustable)" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "879 W/m2" },
      { label: "Input Power Typical", value: "293 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      {
        label: "Working Temperature/Humidity",
        value: "-20C-50C / 10%-80%RH (No Condensation)",
      },
      {
        label: "Storage Temperature/Humidity",
        value: "-20C-55C / 10%-85%RH (No Condensation)",
      },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
  {
    slug: "p5-outdoor-led-display-screen",
    title: "P5 Outdoor LED Display Screen",
    category: "Outdoor",
    pixelPitch: "P5",
    price: "3,000 - 4,800",
    image: "/images/Outdoor-LED-Display/p5-outdoor-led-display-screen.webp",
    shortDescription:
      "P5 outdoor LED display screen with SMD1921 LED technology, bright output, and stable outdoor advertising performance.",
    description:
      "The P5 outdoor LED display screen features a 5mm pixel pitch, SMD1921 LED technology, 64x32 module resolution, 40000 dot/m2 pixel density, 4500-5000 cd/m2 brightness, 3840Hz refresh rate, and 5000:1 contrast ratio. It is suitable for outdoor billboards, storefront signage, transport displays, roadside advertising, event screens, and commercial digital signage projects.",
    features: [
      "5mm pixel pitch for outdoor advertising screens",
      "SMD1921 LED technology with 40000 dot/m2 pixel density",
      "4500-5000 cd/m2 brightness for clear outdoor visibility",
      "3840Hz refresh rate with 12-14 bit processing depth",
      "Reliable 100000-hour lifespan for fixed installations",
    ],
    specifications: [
      { label: "Pixel Pitch", value: "5mm" },
      { label: "LED Type", value: "SMD1921" },
      { label: "Module Resolution", value: "64x32 = 2048 Pixels" },
      { label: "Pixel Density", value: "40000 dot/m2" },
      { label: "Module Size", value: "W320mm x H160mm x D18mm" },
      { label: "Module Weight", value: "0.48+/-0.02kg" },
      { label: "HUB", value: "HUB75" },
      { label: "Single-dot Brightness Calibration", value: "Support" },
      { label: "Brightness", value: "4500-5000 cd/m2" },
      { label: "Color Temperature", value: "6500K (1000K-9500K Adjustable)" },
      { label: "Beam Angle", value: "140deg / 140deg" },
      { label: "Brightness/Color Uniformity", value: ">=98%" },
      { label: "Contrast Ratio", value: "5000:1" },
      { label: "Input Power Max", value: "879 W/m2" },
      { label: "Input Power Typical", value: "293 W/m2" },
      { label: "Power Supply Input Voltage", value: "AC90-132V / AC186-264V, 47-63Hz" },
      { label: "Frame Changing Frequency", value: "60Hz" },
      { label: "Refresh Rate", value: "3840Hz" },
      { label: "Processing Depth", value: "12-14 Bit" },
      { label: "Video Support", value: "2K HD, 4K UHD" },
      { label: "Life Span", value: "100000 Hours" },
      {
        label: "Working Temperature/Humidity",
        value: "-20C-50C / 10%-80%RH (No Condensation)",
      },
      {
        label: "Storage Temperature/Humidity",
        value: "-20C-55C / 10%-85%RH (No Condensation)",
      },
      { label: "Certification", value: "BIS / CE / CB / ROHS / EAC" },
    ],
  },
];

export const ledProducts: LedProduct[] = ledProductData;

export function getLedProductBySlug(slug: string) {
  return ledProducts.find((product) => product.slug === slug);
}

export function getLedProductPath(product: Pick<LedProduct, "slug">) {
  return `/product/${product.slug}`;
}
